name: Release & Publish

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Run validation
        run: npm run validate

      - name: Build project
        run: npm run build

      - name: Extract release notes
        id: extract-release-notes
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

          # Extract release notes from CHANGELOG.md if it exists
          if [ -f CHANGELOG.md ]; then
            sed -n "/^## \[$VERSION\]/,/^## /p" CHANGELOG.md | head -n -1 | tail -n +2 > release-notes.md
          else
            echo "Release $VERSION" > release-notes.md
          fi

          # Ensure release-notes.md has proper formatting
          echo "" >> release-notes.md

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.extract-release-notes.outputs.VERSION }}
          body_path: release-notes.md
          draft: false
          prerelease: false

      - name: Publish to npm
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Post-release notification
        run: |
          echo "🎉 Successfully published version ${{ steps.extract-release-notes.outputs.VERSION }} to npm!"
          echo "📦 Package: https://www.npmjs.com/package/@jamesjfoong/github-pr-review-mcp"
          echo "📋 Release: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
